# Generated by Django 2.2 on 2019-06-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
    ]
